### PR TITLE
Increase backoff steps and reduce factor

### PR DESCRIPTION
**Pull request by zorro786**
The new retry times would be (approximately):
10, 15, 22.5, 33, 50, 75 which sum to about 207 seconds. This is to overcome leader registration times with Mesos that we have seen around 180 seconds.

### CODE REVIEW

**Comment by ridv** [comment]
This only changes it for Australis btw

**Comment by lenhattan86** [comment]
Can you add new parameters for users to change these?

**Comment by zorro786** [comment]
Since this is temporary until we fix timeout issue I thought to make a change here. Doesn't everyone use Australis to deploy jobs (QA etc.)?

**Comment by zorro786** [comment]
Closing this based on discussion.

**Pull request closed without merging**
